# Generated by Django 5.0.1 on 2024-03-31 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_group_group_members_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.ImageField(default='group_default.jpeg', upload_to='group_images'),
        ),
    ]
