# Generated by Django 5.0.1 on 2024-03-31 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_group_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='icon',
            new_name='profile_img',
        ),
    ]
